FROM ubuntu:focal

RUN apt update

RUN apt install -y python3-pip

RUN apt-get -y upgrade 

RUN pip3 install flask requests

RUN mkdir -p /app
WORKDIR /app

COPY web.py /app/web.py
COPY templates /app/templates
COPY static /app/static 

RUN mkdir -p /app/static/{js,css,img}
COPY static/css/style.css app/static/css/style.css
COPY static/js/script.js app/static/js/script.js
COPY static/js/andic_dicts.json app/static/js/andic_dicts.json
COPY static/img/fon.png app/static/img/fon.png

CMD ["python3", "web.py"]

EXPOSE 5000